### ISSUE TITLE
Feature: passing timeout from Python to server

### ISSUE THREAD

**Issue by UniverseFly** [cassanof/code_exec_server#1]
Feature request!

Currently, rasing a timeout error on the client does not necessarily terminate the process on the server since timeout is hardcoded in the server code. This seems to cause a wrong estimation of the number of running processes from the client and excessive server load, even though the semaphore is applied.

As an example of parallel code execution, if I have a queue of fixed number of processes and everytime a process time outs a new process is added, with the current implementation, the number of running processes can be much larger than the queue size.

**Comment by cassanof** [comment]
Yep, understood! I'll make the timeout be a json param. 

Do you think a timeout on the client-side should exist? The reason why I wanted it on both sides is because of the semaphore. I will make it optional

**Comment by UniverseFly** [comment]
Nice! Yeah, optional sounds a great design choice.

**Comment by cassanof** [comment]
should be gtg!
